{
 "title": "Cluster",
 "tags": [ "Fabric" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, exported_namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_created{exported_namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{exported_namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fabric Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Fabric Statefulset Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{exported_namespace=~\"$namespace\" }",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Fabric Pod - Running/Stopped",
   "type": "table",
   "description": "Shows Pod Running/Pending only",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=~\"Running\"}",
     "legendFormat": "namespace: {{exported_namespace}} |  pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Fabric Pod - Ulimit",
   "type": "table",
   "description": "Shows soft ulimit for every users inside the pod",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "container_ulimits_soft{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "namespace: {{namespace}} |  pod: {{pod}} | container: {{container}}"
    }
   ]
  },
  { "title": "Fabric Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Fabric Pods Running",
   "type": "stat",
   "description": "The Pod has been bound to a node, and all of the containers have been created. At least one container is still running, or is in the process of starting or restarting.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Fabric Pods Pending",
   "type": "stat",
   "description": "The Pod has been accepted by the Kubernetes cluster, but one or more of the containers has not been set up and made ready to run. This includes time a Pod spends waiting to be scheduled as well as the time spent downloading container images over the network.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Fabric Pods Failed",
   "type": "stat",
   "description": "All containers in the Pod have terminated, and at least one container has terminated in failure. That is, the container either exited with non-zero status or was terminated by the system.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Fabric Pods Unknown",
   "type": "stat",
   "description": "For some reason the state of the Pod could not be obtained. This phase typically occurs due to an error in communicating with the node where the Pod should be running.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=\"Unknown\" })"
    }
   ]
  },
  {
   "title": "Fabric Pods Succeeded",
   "type": "stat",
   "description": "All containers in the Pod have terminated in success, and will not be restarted.\n",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace\", phase=\"Succeeded\" })"
    }
   ]
  },
  { "title": "Fabric Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Fabric Containers Restarts",
   "type": "bargauge",
   "description": "Tells how many times the container is restarted or going in crash loop backoff error",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{exported_namespace=~\"$namespace\" ,pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\"}",
     "legendFormat": "{{exported_namespace}} | {{pod}} |  {{container}}"
    }
   ]
  },
  {
   "title": "Fabric Containers Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{exported_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fabric Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{exported_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fabric Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{exported_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fabric Containers Waiting",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{exported_namespace}} | {{container}} |  {{pod}}"
    }
   ]
  },
  {
   "title": "Fabric Containers Restarts (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{pod=~\"$pod\"}[5m]) * 60 * 5) by (pod, container, exported_namespace) > 0",
     "legendFormat": "{{pod}}  |  {{container}} | {{exported_namespace}}"
    }
   ]
  },
  { "title": "Cluster Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    },
    {}
   ]
  },
  { "title": "Cluster Kubernetes API Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Cluster 400",
   "type": "stat",
   "description": "Bad Request",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"400\"})"
    }
   ]
  },
  {
   "title": "Cluster 403",
   "type": "stat",
   "description": "Access to the requested resource is forbidden",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"403\"})"
    }
   ]
  },
  {
   "title": "Cluster 409",
   "type": "stat",
   "description": "Conflict",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"409\"})"
    }
   ]
  },
  {
   "title": "Cluster 422",
   "type": "stat",
   "description": "Unprocessable Entityerror",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"422\"})"
    }
   ]
  },
  {
   "title": "Cluster 500",
   "type": "stat",
   "description": "Internal Server Error server",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"500\"})"
    }
   ]
  },
  {
   "title": "Cluster 503",
   "type": "stat",
   "description": "Service Unavailable",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"503\"})"
    }
   ]
  },
  {
   "title": "Cluster 504",
   "type": "stat",
   "description": "Gateway Timeout server error",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=~\"504\"})"
    }
   ]
  },
  { "title": "Cluster CPU and RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Cluster CPU usage (core requests)",
   "type": "gauge",
   "description": "Cluster CPU usage (core requests)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (core limits)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) / sum (kube_pod_container_resource_limits{unit=\"core\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage (memory requests)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_pod_container_resource_requests{unit=\"byte\" }) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage (memory limits)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_pod_container_resource_limits{unit=\"byte\" }) * 100"
    }
   ]
  },
  {
   "title": "Cluster Total CPU requests",
   "type": "stat",
   "description": "Cluster Total CPU requests",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Cluster Total CPU limits",
   "type": "stat",
   "description": "Cluster Total CPU limits",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Cluster Used CPU (interval)",
   "type": "stat",
   "description": "Cluster Used CPU (interval)",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Cluster Total Memory requests",
   "type": "stat",
   "description": "Cluster Total Memory requests",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Cluster Total Memory limits",
   "type": "stat",
   "description": "Cluster Total Memory limits",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Cluster Used Memory (interval)",
   "type": "stat",
   "description": "Cluster Used Memory (interval)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Cluster Load balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Cluster Ingress",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_ingress_created{}", "legendFormat": "{{ingress}}" }
   ]
  },
  {
   "title": "Cluster Network Load balancer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_service_status_load_balancer_ingress{}",
     "legendFormat": "{{exported_service}} | {{exported_namespace}} | {{hostname}}"
    }
   ]
  },
  { "title": "Cluster PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Cluster PV",
   "type": "bargauge",
   "description": "Number of volumes allocated to each pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_persistentvolume_capacity_bytes{}/1073741824) ",
     "legendFormat": "{{persistentvolume}}"
    }
   ]
  },
  {
   "title": "Cluster PVC",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{}",
     "legendFormat": "namespace: {{exported_namespace}} | pvc: {{persistentvolumeclaim}} |  pod: {{pod}} |  vol: {{volume}}"
    }
   ]
  }
 ]
}