{
 "title": "Nightly Tests",
 "time": { "from": "2023-07-16T07:09:43.444Z", "to": "2023-07-16T07:53:00.180Z" },
 "templating": {
  "list": [
   {
    "name": "module",
    "label": "Module",
    "query": "RM,\nPPM,\nLMData,\nLP,\nCollab"
   },
   { "name": "waitTime", "label": "waitTime", "query": "1000" }
  ]
 },
 "panels": [
  {
   "title": "Data Wrangled",
   "type": "logs",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"logfmt2json\",namespace=\"jenkins-jobs\"} | json | message_WaitTime != \"\" | message_Module_Name=~\"$module\" | message_WaitTime>=$waitTime | line_format \"Module {{.message_Module_Name}} for {{.message_Element_locator}} taking {{.message_WaitTime}}\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Graph Time series: Data Wrangled",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time({application=\"logfmt2json\", namespace=\"jenkins-jobs\"} | json  | message_WaitTime!=\"\" | message_Module_Name=~\"$module\" | message_WaitTime>=$waitTime | unwrap message_WaitTime [$__interval])",
     "legendFormat": "Business name: {{message_Element_business_name}}  for {{message_Element_locator}}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Graph Bar: Data Wrangled",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time({application=\"logfmt2json\", namespace=\"jenkins-jobs\"} | json  | message_WaitTime!=\"\" | message_Module_Name=~\"$module\" | message_WaitTime>=$waitTime | unwrap message_WaitTime [1m])",
     "legendFormat": "{{message_Element_business_name}} | {{message_Element_locator}}",
     "maxLines": 1000
    }
   ]
  },
  { "title": "RAW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "RAW  logs in bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({application=\"nightly-tests\",namespace=\"qa\"}[$__interval])"
    }
   ]
  },
  {
   "title": "RAW  logs lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({application=\"nightly-tests\",namespace=\"qa\"}[$__interval])"
    }
   ]
  },
  {
   "title": "RawData",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{application=\"nightly-tests\",namespace=\"qa\"}"
    }
   ]
  }
 ]
}