{
 "title": "Resources",
 "tags": [ "Fabric" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(kube_ingress_created{ namespace=~\"$namespace\" }, ingress)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Fabric RAM & CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric CPU Usage",
   "type": "timeseries",
   "description": "Total CPU time consumed by all tasks in seconds. This metric is derived from prometheus metric.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*\", image!=\"\", namespace=~\"$namespace\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\"}[5m])) by (pod, container, namespace) / sum(container_spec_cpu_quota{name!~\".*prometheus.*\", image!=\"\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\", namespace=~\"$namespace\"}/container_spec_cpu_period{name!~\".*prometheus.*\", image!=\"\", container!=\"POD\", pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"}) by (pod, container, namespace)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  { "title": "Fabric Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Fabric Network I/O",
   "type": "graph",
   "description": "The network received throughput in Megabits per second. This metric is derived from the Prometheus metric.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$interval])))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "- sort_desc(sum by (pod) (rate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Fabric Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "Fabric Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Fabric Ingress",
   "type": "piechart",
   "description": "Tell number of ingress deployed in cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_ingress_created{ namespace=~\"$namespace\" }",
     "legendFormat": "{{ingress}} | {{tls_host}}"
    }
   ]
  },
  {
   "title": "Fabric Ingress Info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_ingress_path{ingress=~\"$ingress\"}",
     "legendFormat": "Ingress: {{ingress}} | Service Name: {{service_name}} | Service Port {{service_port}} | Path: {{path}}"
    }
   ]
  },
  { "title": "Fabric Container Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Container Network Transmitted Packets/Sec\t",
   "type": "timeseries",
   "description": "Number of packets transmitted per second. This metric is derived from prometheus metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{ pod=~\"$pod\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Packets/Sec",
   "type": "timeseries",
   "description": "Number of bytes received per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{ pod=~\"$pod\", namespace=~\"$namespace\" }[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Throughput (Mbps)\t",
   "type": "timeseries",
   "description": "Network transmitted throughput in Megabits per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Throughput (Mbps)\t",
   "type": "timeseries",
   "description": "The network received throughput in Megabits per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Packets Dropped/Sec\t",
   "type": "timeseries",
   "description": "A number of packets dropped while transmitting per second. This metric is derived from the Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Packets Dropped/Sec",
   "type": "timeseries",
   "description": "Number of packets received per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Error/Sec\t",
   "type": "timeseries",
   "description": "Number of errors encountered while transmitting per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "container_network_transmit_errors_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Error/Sec\t",
   "type": "timeseries",
   "description": "A number of errors were encountered while receiving per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "container_network_receive_errors_total{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  }
 ]
}