version: '3.8'

services:

  # Service for metrics
  victoria-metrics1:
    image: victoriametrics/victoria-metrics:v1.104.0
    container_name: victoria-metrics1
    ports:
      - "8428:8428"
    command:
      - '--retentionPeriod=1'
      - '--storageDataPath=/victoria-metrics-data'
      - '--promscrape.config=/etc/victoria-metrics/prometheus.yml'  # Scrape configuration
    volumes:
      - ./prometheus.yml:/etc/victoria-metrics/prometheus.yml  # Volume for scrape config
    restart: always

  victoria-metrics2:
    image: victoriametrics/victoria-metrics:v1.104.0
    container_name: victoria-metrics2
    ports:
      - "8429:8428"
    command:
      - '--retentionPeriod=1'
      - '--storageDataPath=/victoria-metrics-data'
      - '--promscrape.config=/etc/victoria-metrics/prometheus.yml'  # Scrape configuration
    volumes:
      - ./prometheus.yml:/etc/victoria-metrics/prometheus.yml  # Volume for scrape config
    restart: always

  # Service for logs
  loki1:
    image: grafana/loki:3.0.0
    command: "-config.file=/etc/loki/loki-config.yml"
    container_name: loki1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config1.yml:/etc/loki/loki-config.yml
    restart: always

  loki2:
    image: grafana/loki:3.0.0
    container_name: loki2
    ports:
      - "3200:3200"
    volumes:
      - ./loki-config2.yml:/etc/loki/loki-config.yml
    command: "-config.file=/etc/loki/loki-config.yml"
    restart: always

  
  # Start sending metrics to victoria logs

  # Start generating sample logs
  log-generator:
    image: busybox  # Use a lightweight image to generate logs
    container_name: log-generator
    command: /bin/sh -c "while true; do echo '$(date) Sample log entry' >> /var/log/sample.log; sleep 5; done"
    volumes:
      - ./sample-log:/var/log  # Volume to store the log file
    restart: always

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./sample-log:/var/log  # Volume to read the generated logs
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: always

  # Start sending metrics to VictoriaMetrics using Telegraf
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
