scrape_configs:
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']  # Address of the Telegraf container

  # - job_name: 'alertmanager'
  #   static_configs:
  #     - targets: ['alertmanager1:9093', 'alertmanager2:9093']

  - job_name: grafana1
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana1:3000

  - job_name: grafana2
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana2:3000