version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.0
        container_name: zookeeper
        ports:
            - "32181:2181"
        networks:
            - svastikkka
        environment:
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=INFO
            - ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=INFO
    kafka:
        image: confluentinc/cp-kafka:6.2.0
        container_name: kafka
        ports:
        - "19092:19092"
        networks:
        - svastikkka
        depends_on:
        - zookeeper
        environment:
        - KAFKA_BROKER_ID=2
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
        - KAFKA_LOG4J_ROOT_LOGLEVEL=INFO
        - KAFKA_TOOLS_LOG4J_LOGLEVEL=INFO
    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - "18080:8080"
        networks:
            - svastikkka
        depends_on:
            - kafka
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
networks:
    svastikkka:
        driver: bridge