version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.0
        container_name: zookeeper
        ports:
            - "32181:2181"
        networks:
            - svastikkka
        environment:
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=INFO
            - ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=INFO
    kafka:
        image: confluentinc/cp-kafka:6.2.0
        container_name: kafka
        ports:
        - "19092:19092"
        networks:
        - svastikkka
        depends_on:
        - zookeeper
        environment:
        - KAFKA_BROKER_ID=2
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
        - KAFKA_LOG4J_ROOT_LOGLEVEL=INFO
        - KAFKA_TOOLS_LOG4J_LOGLEVEL=INFO
    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - "18080:8080"
        networks:
            - svastikkka
        depends_on:
            - kafka
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    database:
        image: mongo:4.4
        container_name: mongo
        environment:
            - MONGO_INITDB_DATABASE='svastikkka_db'
        networks:
            - svastikkka
        ports:
            - "27017:27017"
    collab:
        image: docker.cloud.digite.com/digite/attachment-service:dev-latest
        container_name: collab
        environment:
          - runtime-env=dev
          - digite.cloud.fabric.runtime-env=local
          - digite.cloud.collab.service.clamav.port=3310
          - digite.cloud.collab.service.clamav.host=collab-clamav.dev.svc.cluster.local
          - digite.cloud.collab.service.messaging.output.quota.topic-name=fabric-${spring.application.name}-quota-${runtime-env}
          - digite.cloud.collab.service.messaging.output.download-later.topic-name=fabric-${spring.application.name}-downloadlater-${runtime-env}
          - digite.cloud.collab.service.messaging.output.attachment.topic-name=fabric-${spring.application.name}-attachment-${runtime-env}
          - digite.cloud.collab.service.messaging.output.comment.topic-name=fabric-${spring.application.name}-comment-${runtime-env}
          - digite.cloud.collab.service.aws.s3.bucket-name=collab-s3
          - digite.cloud.collab.service.aws.s3.region=us-east-1
          - digite.cloud.collab.service.published-host=https://collab.seswifte2e.digite.com
          - digite.collab.service.download.all.max-instant-download=107374182
          - spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
          - spring.cloud.config.enabled=false
          - spring.cloud.config.discovery.enabled=false
          - spring.cloud.config.server.bootstrap=false
          - spring.cloud.config.import-check.enabled=false
          - spring.cloud.bus.enabled=false
          - spring.cloud.function.definition=quotaMessageConsumer;userProfileConsumer
          - spring.cloud.stream.default.producer.useNativeEncoding=true
          - spring.cloud.stream.default.consumer.useNativeDecoding=true
          - spring.cloud.stream.bindings.input.contentType=application/json
          - spring.cloud.stream.bindings.userProfileConsumer-in-0.contentType=application/json
          - spring.cloud.stream.bindings.userProfileConsumer-in-0.destination=fabric-ups-${runtime-env}
          - spring.cloud.stream.bindings.userProfileConsumer-in-0.group=fabric-${spring.application.name}-ups-consumers-${runtime-env}
          - spring.cloud.stream.bindings.nimbleMessageConsumer-in-0.contentType=application/json
          - spring.cloud.stream.bindings.nimbleMessageConsumer-in-0.destination=alm-nimble-${runtime-env}
          - spring.cloud.stream.bindings.nimbleMessageConsumer-in-0.group=fabric-${spring.application.name}-nimble-consumers-${runtime-env}
          - spring.cloud.stream.kafka.streams.binder.serdeError=logAndContinue
          - spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
          - spring.cloud.stream.kafka.binder.autoCreateTopics=false
          - spring.cloud.stream.kafka.binder.brokers=localhost:19092
          - spring.cloud.stream.kafka.default.producer.configuration.spring.json.add.type.headers=false
          - spring.cloud.stream.kafka.default.producer.configuration.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer
          - spring.cloud.stream.kafka.default.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
          - spring.cloud.stream.kafka.default.producer.configuration.max.block.ms=100
          - spring.cloud.stream.kafka.default.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
          - spring.cloud.stream.kafka.default.consumer.configuration.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
          - spring.application.name=collab-service
          - spring.cloud.vault.token=123

          - spring.sleuth.reactor.enabled=false
          - spring.sleuth.enabled=true
          - spring.sleuth.otel.config.trace-id-ratio-based=1
          - spring.sleuth.otel.exporter.otlp.endpoint=http://localhost:4317
          - spring.cloud.discovery.enabled=false
          - spring.cloud.bootstrap.enabled=false
          #data.mongodb.uri=mongodb://localhost:27018/baas_db
          - spring.data.mongodb.auto-index-creation=true
          - spring.data.mongodb.database=baas_db
          - spring.data.mongodb.host=localhost
          - spring.data.mongodb.port=27018
          - logging.level.root=DEBUG
        networks:
            - svastikkka
        ports:
            - "28080:28080"
networks:
    svastikkka:
        driver: bridge
