version: '3.1'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"   # InfluxDB web UI
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    # volumes:
      # - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      - svastikkka
  chronograf:
    image: chronograf:1.8
    container_name: chronograf
    ports:
      - "8881:8888"  # Chronograf web UI
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    networks:
      - svastikkka

  kapacitor:
    image: kapacitor:1.5
    container_name: kapacitor
    ports:
      - "9092:9092"  # Kapacitor API
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_ENABLED=true
      - KAPACITOR_INFLUXDB_0_NAME=default
      - KAPACITOR_HTTP_AUTH_USERNAME=admin
      - KAPACITOR_HTTP_AUTH_PASSWORD=admin
    volumes:
      - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    depends_on:
      - influxdb
    networks:
      - svastikkka
      
  telegraf:
    image: telegraf:1.18
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    depends_on:
      - influxdb
    # environment:
    #   # - HOST_PROC=/host/proc
    #   # - HOST_SYS=/host/sys
    #   # - HOST_ETC=/host/etc
    #   # - HOST_MOUNT_PREFIX=/host
    networks:
      - svastikkka
networks:
  svastikkka:
    driver: bridge
