{
 "title": "Fabric Apps",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, exported_namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_created{exported_namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{exported_namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(kube_ingress_created{ exported_namespace=~\"$namespace\" }, ingress)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Requests Average Duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod, uri)(http_server_requests_seconds_sum{pod=~\"$pod\", uri!~\"/actuator/.+\"}) / sum by(pod, uri)(http_server_requests_seconds_count{pod=~\"$pod\", uri!~\"/actuator/.+\"})",
     "legendFormat": "{{ pod }} | {{ uri }}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", uri!~\".*actuator.*\"}[$__range])) by (namespace, pod)"
    }
   ]
  },
  { "title": "Fabric Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Fabric Network I/O",
   "type": "graph",
   "description": "The network received throughput in Megabits per second. This metric is derived from the Prometheus metric.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$interval])))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "- sort_desc(sum by (pod) (rate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Fabric RAM & CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Fabric Memory Usage",
   "type": "bargauge",
   "description": "Give details regarding memory usage of each POD.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\"}/1073741824)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fabric CPU Usage",
   "type": "graph",
   "description": "Total CPU time consumed by all tasks in seconds. This metric is derived from prometheus metric.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*\", image!=\"\", namespace=~\"$namespace\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\"}[5m])) by (pod, container, namespace) /\nsum(container_spec_cpu_quota{name!~\".*prometheus.*\", image!=\"\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\", namespace=~\"$namespace\"}/container_spec_cpu_period{name!~\".*prometheus.*\", image!=\"\", container!=\"POD\", pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"}) by (pod, container, namespace)"
    }
   ]
  },
  { "title": "Fabric Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Fabric Server Requests Seconds Max",
   "type": "timeseries",
   "description": "Gives us the maximum duration of each type of inbound HTTP request.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{namespace=~\"$namespace\", pod=~\"$pod\", uri!~\"/actuator/.+\" }",
     "legendFormat": "{{namespace}} | {{pod}} | {{status}} | {{method}} | {{outcome}} | PATH {{uri}}"
    }
   ]
  },
  { "title": "Fabric Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Fabric Ingress",
   "type": "piechart",
   "description": "Tell number of ingress deployed in cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_ingress_created{ exported_namespace=~\"$namespace\" }",
     "legendFormat": "{{ingress}} | {{tls_host}}"
    }
   ]
  },
  {
   "title": "Fabric Ingress Info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_ingress_path{ingress=~\"$ingress\"}",
     "legendFormat": "Ingress: {{ingress}} | Service Name: {{service_name}} | Service Port {{service_port}} | Path: {{path}}"
    }
   ]
  },
  { "title": "Fabric Container Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Container Network Transmitted Packets/Sec\t",
   "type": "timeseries",
   "description": "Number of packets transmitted per second. This metric is derived from prometheus metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{ pod=~\"$pod\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Packets/Sec",
   "type": "timeseries",
   "description": "Number of bytes received per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{ pod=~\"$pod\", namespace=~\"$namespace\" }[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Throughput (Mbps)\t",
   "type": "timeseries",
   "description": "Network transmitted throughput in Megabits per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Throughput (Mbps)\t",
   "type": "timeseries",
   "description": "The network received throughput in Megabits per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Packets Dropped/Sec\t",
   "type": "timeseries",
   "description": "A number of packets dropped while transmitting per second. This metric is derived from the Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Packets Dropped/Sec",
   "type": "timeseries",
   "description": "Number of packets received per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Transmitted Error/Sec\t",
   "type": "timeseries",
   "description": "Number of errors encountered while transmitting per second. This metric is derived from prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "container_network_transmit_errors_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Received Error/Sec\t",
   "type": "timeseries",
   "description": "A number of errors were encountered while receiving per second. This metric is derived from Prometheus metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "container_network_receive_errors_total{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  }
 ]
}