{
 "title": "Fabric JVM",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, exported_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{exported_namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP Response Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=~\"$namespace\", status!~\"5..\"}[$interval]))/sum(rate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", status!~\"5..\"}[$interval]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{pod=~\"$pod\", namespace=~\"$namespace\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Total HTTP Write Requests success",
   "type": "timeseries",
   "description": "PUT + POST + PATCH + DELETE with 2xx success response",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", status=~\"^(1|2|3).*\", method=~\"PUT|POST|PATCH|DELETE\", uri!~\".*actuator.*\"}[2m])) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Total HTTP Read Requests success",
   "type": "timeseries",
   "description": "GET + OPTION +HEAD with 2xx success response",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", status=~\"^(1|2|3).*\", method=~\"GET|OPTION|HEAD\", uri!~\".*actuator.*\"}[2m])) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Total HTTP Write Requests Failures",
   "type": "timeseries",
   "description": "PUT + POST + PATCH + DELETE with 4xx client error or 5xx server error",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", status=~\"^(5|4).*\", method=~\"PUT|POST|PATCH|DELETE\", uri!~\".*actuator.*\"}[2m])) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Total HTTP Read Requests Failures",
   "type": "timeseries",
   "description": "GET + OPTION +HEAD with 4xx client error or 5xx server error",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=~\"$namespace\", status=~\"^(4|5).*\", method=~\"GET|OPTION|HEAD\" , uri!~\".*actuator.*\"}[2m])) by(method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}} | system"
    },
    {
     "expr": "process_cpu_usage{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}} | process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{pod=\"$pod\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{namespace}} | {{pod}} | process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Log counts except debug and info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(log4j2_events_total{pod=~\"$pod\", namespace=~\"$namespace\", level=~\"error|fatal|trace|warn\"}[2m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Kafka Consumer Connection Count Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_consumer_connection_count_total{pod=~\"$pod\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Kafka Consumer Request/Sec Rate",
   "type": "stat",
   "description": "The number of requests send per second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_request_rate{pod=~\"$pod\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Total Requests",
   "type": "stat",
   "description": "The total number of fetch requests.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_total{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Kafka Records Consumed/Sec Rate",
   "type": "timeseries",
   "description": "The average number of records consumed per second for a topic.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | Topic: {{topic}} | Clinet ID: {{client_id}} | Spring ID:{{spring_id}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Requests/Sec Rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}} | {{pod}}",
     "visualQuery": {
      "labels": [
       { "label": "namespace", "op": "=", "value": "qa" }
      ],
      "metric": "kafka_consumer_fetch_manager_fetch_rate",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency Max",
   "type": "timeseries",
   "description": "The max time taken for any fetch request.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}} | {{pod}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "nightly-domain-data-api-5d75b6dc4-wpzx4"
       }
      ],
      "metric": "kafka_consumer_outgoing_byte_total",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency Avg",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Mongodb Driver Commands Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_driver_commands_seconds_max{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | {{command}} | {{collection}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "domain-data-api-9857d678d-56ssd"
       },
       { "label": "namespace", "op": "=", "value": "dev" }
      ],
      "metric": "mongodb_driver_commands_seconds_max",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Mongodb Driver Pool Waitqueuesize",
   "type": "timeseries",
   "description": "The current size of the wait queue for a connection from the pool",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "mongodb_driver_pool_waitqueuesize{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | {{namespace}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "domain-data-api-9857d678d-56ssd"
       },
       { "label": "namespace", "op": "=", "value": "dev" }
      ],
      "metric": "mongodb_driver_commands_seconds_max",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Mongodb Driver Pool Checkedout",
   "type": "timeseries",
   "description": "Count of connections that are currently in use",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "mongodb_driver_pool_checkedout{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | {{namespace}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "domain-data-api-9857d678d-56ssd"
       },
       { "label": "namespace", "op": "=", "value": "dev" }
      ],
      "metric": "mongodb_driver_commands_seconds_max",
      "operations": []
     }
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "CPU time used by GC",
   "type": "stat",
   "description": "An approximation of the percent of CPU time used by GC activities over the last lookback period or since monitoring began, whichever is shorter, in the range [0..1]",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap Gain Byte Size",
   "type": "stat",
   "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM GC Max Data Size Bytes",
   "type": "stat",
   "description": "Max size of long-lived heap memory pool",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Long Lived Heap Pool",
   "type": "stat",
   "description": "Size of long-lived heap memory pool after reclamation",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Gc Pause Duration In Seconds",
   "type": "timeseries",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Action: {{action}} | Cause: {{cause}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 125 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 133 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{pod=~\"$pod\",namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}