{
 "title": "Kivi Servers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "hulk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulk" }
     ]
    },
    {
     "alias": "hulkbuster",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulkbuster" }
     ]
    },
    {
     "alias": "loki",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "loki" }
     ]
    },
    {
     "alias": "spiderman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "spiderman" }
     ]
    },
    {
     "alias": "marvel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "marvel" }
     ]
    },
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "kivisec_220",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kivisec_220" }
     ]
    },
    {
     "alias": "comp-212",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "comp-212" }
     ]
    },
    {
     "alias": "devil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "devil" }
     ]
    },
    {
     "alias": "fury",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "fury" }
     ]
    },
    {
     "alias": "groot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "groot" }
     ]
    },
    {
     "alias": "ironman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "ironman" }
     ]
    },
    {
     "alias": "jarvis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "jarvis" }
     ]
    },
    {
     "alias": "kivi-PC-25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kivi-PC-25" }
     ]
    },
    {
     "alias": "kiwi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kiwi" }
     ]
    },
    {
     "alias": "parker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "parker" }
     ]
    },
    {
     "alias": "remo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "remo" }
     ]
    },
    {
     "alias": "rocket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "rocket" }
     ]
    }
   ]
  },
  {
   "title": "system down =0",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"packets_received\") FROM \"ping\" WHERE (\"host\"::tag = 'thor') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "loki",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "loki" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "marvel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "marvel" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "hulk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulk" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "hulkbuster",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulkbuster" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "ironman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "ironman" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "superman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "superman" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "spiderman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "spiderman" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "kivisec_220",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kivisec_220" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "jarvis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "jarvis" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "remo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "remo" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "devil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "devil" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "kiwi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kiwi" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "shaktimaan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "shaktimaan" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "rocket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "rocket" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "parker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "parker" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "blade",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "blade" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "comp-212",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "comp-212" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "fury",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "fury" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "groot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "groot" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "loki",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "loki" }
     ]
    },
    {
     "alias": "marvel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulk" }
     ]
    },
    {
     "alias": "hulk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "marvel" }
     ]
    },
    {
     "alias": "hulkbuster",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hulkbuster" }
     ]
    },
    {
     "alias": "ironman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "ironman" }
     ]
    },
    {
     "alias": "superman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "superman" }
     ]
    },
    {
     "alias": "spiderman",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "spiderman" }
     ]
    },
    {
     "alias": "blade",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "blade" }
     ]
    },
    {
     "alias": "jarvis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "jarvis" }
     ]
    },
    {
     "alias": "groot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "groot" }
     ]
    },
    {
     "alias": "remo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "remo" }
     ]
    },
    {
     "alias": "devil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "devil" }
     ]
    },
    {
     "alias": "kiwi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kiwi" }
     ]
    },
    {
     "alias": "rocket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "rocket" }
     ]
    },
    {
     "alias": "shaktimaan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "shaktimaan" }
     ]
    },
    {
     "alias": "kivisec_220",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "kivisec_220" }
     ]
    },
    {
     "alias": "parker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "parker" }
     ]
    },
    {
     "alias": "fury",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "fury" }
     ]
    }
   ]
  },
  {
   "title": "Network Error (err_out)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "KIVI-NEW24",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='KIVI-NEW24') AND $timeFilter GROUP BY time($__interval) FILL(null)"
    },
    {
     "alias": "blade",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='blade') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "kiwi",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='kiwi') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "rocket",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='rocket') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "jarvis",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='jarvis') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "remo",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='remo') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "devil",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='devil') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "shakitmaan",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='shaktimaan') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "marvel",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='marvel') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "superman",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='superman') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "loki",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='loki') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "spiderman",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='spiderman') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "parker",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='parker') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "ironman",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='ironman') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "groot",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='groot') GROUP BY time(10m) FILL(null)"
    },
    {
     "alias": "fury",
     "query": "SELECT mean(\"err_out\") AS \"mean_err_out\" FROM \"telegraf\".\"autogen\".\"net\" WHERE  ( \"host\"='fury') GROUP BY time(10m) FILL(null)"
    }
   ]
  },
  {
   "title": "service",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "alias": "testing.service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemd_units",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "testing.service" }
     ]
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'thor') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "loki",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'loki') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "marvel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'marvel') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "hulk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'hulk') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "hulkbuster",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'hulkbuster') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "kivisec_220",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'kivisec_220') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "KIVI-NEW24",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'KIVI-NEW24') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "comp-212",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'comp-212') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    },
    {
     "alias": "devil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" = 'devil') AND $timeFilter GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    }
   ]
  },
  {
   "title": "Logs Metrics",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "alias": "thor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "query": "SELECT last(\"data\") AS \"last_data\"\nFROM \"telegraf\".\"autogen\".\"syslog\"\nWHERE $timeFilter AND \"path\"='/var/log/syslog' AND \"host\"='thor' AND \"data\" =~ /.*error|ERROR.*/\nGROUP BY time(10m), last_data FILL(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" }
     ]
    }
   ]
  },
  {
   "title": "Network Speed (bytes_sent)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "groot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 10s) FROM \"net\" WHERE (\"host\"::tag = 'groot' AND \"interface\"::tag = 'bond0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "thor" },
      { "condition": "AND", "key": "interface::tag", "operator": "=", "value": "enp8s0" }
     ]
    }
   ]
  }
 ]
}