version: '3.3'

networks:
  monitoring:
    driver: bridge

services:
  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    networks:
      - monitoring

  mimir-1:
    image:  grafana/mimir:latest
    command: ["-config.file=/etc/mimir/mimir.yml"]
    hostname: mimir-1
    ports:
      - 9001:9009
    depends_on:
      - minio
    volumes:
      - ./mimir/mimir.yml:/etc/mimir/mimir.yml
      - ./mimir/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
    networks:
      - monitoring

  mimir-2:
    image:  grafana/mimir:latest
    command: ["-config.file=/etc/mimir/mimir.yml"]
    hostname: mimir-2
    ports:
      - 9002:9009
    depends_on:
      - minio
    volumes:
      - ./mimir/mimir.yml:/etc/mimir/mimir.yml
      - ./mimir/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
    networks:
      - monitoring

  mimir-3:
    image:  grafana/mimir:latest
    command: ["-config.file=/etc/mimir/mimir.yml"]
    hostname: mimir-3
    ports:
      - 9003:9009
    depends_on:
      - minio
    volumes:
      - ./mimir/mimir.yml:/etc/mimir/mimir.yml
      - ./mimir/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yaml:/etc/prometheus/rules.yaml
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring
    depends_on:
      - "mimir-1"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring