version: '3.3'
services:
  zookeeper:
    container_name: zookeeper101
    image: confluentinc/cp-zookeeper:6.2.6
    ports:
    - "12181:2181"
    - "12888:2888"
    - "13888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=INFO
      - ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=INFO
  kafka1:
    image: confluentinc/cp-kafka:6.2.6
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
    - zookeeper
    ports:
    - "19091:9091"
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.105:19091
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper101:2181
    - KAFKA_BROKER_ID=1
    - BOOTSTRAP_SERVERS=192.168.0.105:19091,192.168.0.105:19092,192.168.0.123:9093
    - ZOOKEEPER=zookeeper101:2181
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2
  kafka2:
    image: confluentinc/cp-kafka:6.2.6
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
    - zookeeper
    ports:
    - "19092:9092"
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.105:19092
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper101:2181
    - KAFKA_BROKER_ID=2
    - BOOTSTRAP_SERVERS=192.168.0.105:19091,192.168.0.105:19092,192.168.0.123:9093
    - ZOOKEEPER=zookeeper101:2181
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2