name: data_auditing_env
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - pip=23.2.1
  - pip:
    - arcticdb==4.2.1
    - pyarrow==12.0.1
    - fastparquet==2023.7.0
    - pytest==7.4.0
    - mock==5.1.0
    - mypy==1.5.1
    - pandas-stubs==2.0.3.230814
    - coverage==7.3.0
    - pytest-cov==4.1.0
    - pandas==2.0.0
    - py_vollib==1.0.1
    - scipy==1.11.4
    - black==23.9.1
    - flake8==6.1.0 
    - minio==7.2.3               
    - pytest-mock==3.12.0
    - bcrypt==4.1.2