version: '3.7'
services:
  vault:
    image: hashicorp/vault:latest
    restart: always
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: "vault server -dev"
