version: '3.7'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"  # Jaeger Thrift
      - "14268:14268"  # Jaeger collector HTTP endpoint
      - "14250:14250"  # Jaeger gRPC endpoint
      # - "4317:4317"
      # - "4318:4318"
    environment:
      # COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true

  # otel-agent:
  #   image: otel/opentelemetry-collector:latest
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   depends_on:
  #     - jaeger
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
     - 13306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=mydb

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
        - "32181:2181"
    environment:
        - ZOOKEEPER_SERVER_ID=1
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=INFO
        - ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=INFO

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
    - "19092:19092"
    depends_on:
    - zookeeper
    environment:
    - KAFKA_BROKER_ID=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
    - KAFKA_LOG4J_ROOT_LOGLEVEL=INFO
    - KAFKA_TOOLS_LOG4J_LOGLEVEL=INFO

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
        - "18080:8080"
    depends_on:
        - kafka
    environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181