version: '3'
services:
  graphite:
    ports:
    - 8081:80
    - 2003-2004:2003-2004
    - 7002:7002
    - 8125:8125/udp
    - 8126:8126
    - 2023-2024:2023-2024
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: monitoring=true
    tty: true
    image: graphiteapp/graphite-statsd
    # volumes:
    # - graphite-data:/opt/graphite/storage
    stdin_open: true
    environment:
    - COLLECTD=1
    - GRAPHITE_DEBUG=1
    - REDIS_TAGDB=1
    - BRUBECK=1

  grafana:
    image: grafana/grafana:latest
    # pull_policy: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - 9090:9090
  #   volumes:
  #     - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml

  load-balancer:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9009:9009