version: '3'
services:
  mysql1:
    container_name: master
    image: mysql:8.0
    ports:
     - 13306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=mydb
    volumes:
      - ./mysql-master/config/:/etc/mysql/conf.d/
    networks:
      - svastikkka
  mysql2:
    container_name: slave
    image: mysql:8.0
    ports:
     - 23306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DATABASE=mydb
    volumes:
      - ./mysql-slave/config/:/etc/mysql/conf.d/
    links:
      - mysql1
    networks:
      - svastikkka
networks:
  svastikkka: