{
 "title": "Cluster",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mongodb_connections_available, cl_name)"
    }
   },
   {
    "name": "replicaSet",
    "query": {
     "query": "label_values(mongodb_connections_available, rs_nm)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(mongodb_connections_available, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_uptimeMillis{cl_name=\"$cluster\"}",
     "legendFormat": "{{rs_state}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$cluster-\\\\d\",container=\"mongod\"}[$__range])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "description": "Reports the read concern level specified by query operations to the mongod instance since it last started.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_current{cl_name=\"$cluster\"}",
     "legendFormat": "Current - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of  connections.current to understand the connection load on the database.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_available{cl_name=\"$cluster\"}",
     "legendFormat": "Available - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Open Read Concerns",
   "type": "piechart",
   "description": "Reports the read concern level specified by query operations to the mongod instance since it last started.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_available{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "Available | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_linearizable{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "Linearizable  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_local{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "Local  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_majority{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "Majority  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_snapshot{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "Snapshot  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opReadConcernCounters_none{cl_name=\"$cluster\",rs_nm=\"$replicaSet\"}[$__range])) by (rs_state)",
     "legendFormat": "None  | {{rs_state}}"
    }
   ]
  },
  {
   "title": "Open Write Concerns",
   "type": "piechart",
   "description": "Reports the write concern level specified by query operations to the mongod instance since it last started.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_available{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Available | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_linearizable{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Linearizable  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_local{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Local  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_majority{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Majority  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_snapshot{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Snapshot  | {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_opWriteConcernCounters_none{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "None  | {{rs_state}}"
    }
   ]
  },
  {
   "title": "Read Latencies Primary",
   "type": "piechart",
   "description": "A histogram of Number of Documents vs Latencies for read operations",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_1_100_249us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "0.1ms-.249ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_2_250_499us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": ".25ms-.49ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_3_500_999us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": ".5ms-.99ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_4_1000_9999us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "1ms-9.9us"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_5_10000us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "10ms and above"
    }
   ]
  },
  {
   "title": "Write Latencies Primary",
   "type": "piechart",
   "description": "A histogram of Number of Documents vs Latencies for read operations",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_1_100_249us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "0.1ms-.249ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_2_250_499us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": ".25ms-.49ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_3_500_999us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": ".5ms-.99ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_4_1000_9999us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "1ms-9.9us"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_5_10000us{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\", rs_state=\"1\"}[$__range])",
     "legendFormat": "10ms and above"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "bargauge",
   "description": "Total Open cursors, cursors pinned and cursors manually set to high timeout",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_metrics_cursor_open_total{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Total - {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_metrics_cursor_open_pinned{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "Pinned - {{rs_state}}"
    },
    {
     "expr": "sum(increase(mongodb_metrics_cursor_open_noTimeout{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])) by (rs_state)",
     "legendFormat": "No Timeout - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Global Locks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "mongodb_globalLock_activeClients_readers{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}",
     "legendFormat": "Readers"
    },
    {
     "expr": "mongodb_globalLock_activeClients_writers{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}",
     "legendFormat": "Writers"
    }
   ]
  },
  {
   "title": "Read Latencies Secondary",
   "type": "piechart",
   "description": "A histogram of Number of Documents vs Latencies for read operations",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_1_100_249us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "0.1ms-.249ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_2_250_499us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": ".25ms-.49ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_3_500_999us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": ".5ms-.99ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_4_1000_9999us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "1ms-9.9us"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_read_latency_histogram_bucket_5_10000us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "10ms and above"
    }
   ]
  },
  {
   "title": "Write Latencies Secondary",
   "type": "piechart",
   "description": "A histogram of Number of Documents vs Latencies for read operations",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_1_100_249us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "0.1ms-.249ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_2_250_499us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": ".25ms-.49ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_3_500_999us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": ".5ms-.99ms"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_4_1000_9999us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "1ms-9.9us"
    },
    {
     "expr": "delta(mongodb_wiredTiger_perf_operation_write_latency_histogram_bucket_5_10000us{cl_name=\"$cluster\", rs_nm=\"$replicaSet\", rs_state=\"2\"}[$__range])",
     "legendFormat": "10ms and above"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_transactions_currentActive{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "increase(mongodb_transactions_totalAborted{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Aborted"
    },
    {
     "expr": "mongodb_transactions_retriedStatementsCount{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}",
     "legendFormat": "Retried Statements"
    },
    {
     "expr": "mongodb_transactions_retriedCommandsCount{cl_name=~\"$cluster\",rs_nm=~\"$replicaSet\"}",
     "legendFormat": "Retried Commands"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "timeseries",
   "description": "Number of Replication Operations run over the given period",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(mongodb_opcountersRepl_query{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Read - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcountersRepl_getmore{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "GetMore - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcountersRepl_insert{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Insert - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcountersRepl_delete{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Delete - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcountersRepl_update{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Update - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Mongo Operations",
   "type": "timeseries",
   "description": "Summary of number of operations executed in the given time range",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "increase(mongodb_opcounters_query{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Read - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcounters_getmore{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "GetMore - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcounters_insert{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Insert - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcounters_update{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Update - {{rs_state}}"
    },
    {
     "expr": "increase(mongodb_opcounters_delete{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}[$__rate_interval])",
     "legendFormat": "Delete - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Write Conflicts",
   "type": "timeseries",
   "description": "The total number of queries that encountered write conflicts.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_metrics_operation_writeConflicts{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}",
     "legendFormat": "{{cl_name}}-{{rs_nm}}-{{rs_state}}"
    }
   ]
  },
  {
   "title": "Scan And Order",
   "type": "timeseries",
   "description": "The total number of queries that return sorted numbers that cannot perform the sort operation using an index.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_metrics_operation_scanAndOrder{cl_name=~\"$cluster\", rs_nm=~\"$replicaSet\"}",
     "legendFormat": "{{cl_name}}-{{rs_nm}}-{{rs_state}}"
    }
   ]
  }
 ]
}