{
 "title": "HTTP",
 "tags": [ "Fabric" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\", uri!~\".*actuator.*\"}[$__rate_interval])) by (pod, uri, method) != 0",
     "legendFormat": "{{uri}} - {{ method }}"
    }
   ]
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Max Response Times",
   "type": "timeseries",
   "description": "Max response times per URI per app, including error responses.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{namespace=~\"$namespace\",pod=~\"$pod\", uri!~\".*actuator.*\"} > 0",
     "legendFormat": "{{uri}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "timeseries",
   "description": "Average duration of requests per pod per URI.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\", uri!~\".*actuator.*\"}[$__rate_interval]) / increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\", uri!~\".*actuator.*\"}[$__rate_interval]) > 0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Write Requests Failures",
   "type": "timeseries",
   "description": "PUT + POST + PATCH + DELETE with 4xx client error or 5xx server error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"^(5|4).*\", method=~\"PUT|POST|PATCH|DELETE\", uri!~\".*actuator.*\"}[$__rate_interval])",
     "legendFormat": "{{app_kubernetes_io_service}} - {{uri}} - {{ method }} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Read Requests Failures",
   "type": "timeseries",
   "description": "GET + OPTION +HEAD with 4xx client error or 5xx server error",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"^(5|4).*\", method=~\"PUT|POST|PATCH|DELETE\", uri!~\".*actuator.*\"}[$__rate_interval])",
     "legendFormat": "{{app_kubernetes_io_service}} - {{uri}} - {{ method }} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Write Requests success",
   "type": "timeseries",
   "description": "PUT + POST + PATCH + DELETE with 2xx success response",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"^(1|2|3).*\", method=~\"PUT|POST|PATCH|DELETE\", uri!~\".*actuator.*\"}[$__rate_interval])) by(uri,method), 0.5) > 0",
     "legendFormat": "{{uri}} - {{ method }}"
    }
   ]
  },
  {
   "title": "Total Read Requests success",
   "type": "timeseries",
   "description": "GET + OPTION +HEAD with 2xx success response",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"^(1|2|3).*\", method=~\"GET|OPTION|HEAD\", uri!~\".*actuator.*\"}[$__rate_interval])) by(pod, uri, method) > 0",
     "legendFormat": "{{uri}} - {{ method }}"
    }
   ]
  }
 ]
}