{
 "title": "JVM",
 "tags": [ "JVM" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Select pod to see uptime.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Memory Allocation",
   "type": "timeseries",
   "description": "Total permissible and current allocated memory per pd.",
   "gridPos": { "h": 15, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "timeseries",
   "description": "Average memory consumption by app containers in each pod.",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "OOM Restart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{exported_namespace=\"uat\",pod=\"fabric-ppm-service-86bc4bdc46-4bsqt\", reason=\"OOMKilled\"}"
    }
   ]
  },
  {
   "title": "Error Restart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{exported_namespace=~\"$namespace\",pod=\"$pod\", reason=\"Error\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "system_cpu_count{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | system"
    },
    {
     "expr": "process_cpu_usage{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | process"
    }
   ]
  },
  {
   "title": "Fatal, Error and Warn logs count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(log4j2_events_total{pod=~\"$pod\", namespace=~\"$namespace\", level=~\"error|fatal|warn\"}[$__rate_interval])) by (pod,level)",
     "legendFormat": "{{pod}} - {{ level }}"
    }
   ]
  },
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Repository Method Execution Time",
   "type": "timeseries",
   "description": "Total time taken per method per repository, a high value indicates perf issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(spring_data_repository_invocations_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{repository}} - {{method}}"
    }
   ]
  },
  {
   "title": "Repository Method Execution Count",
   "type": "timeseries",
   "description": "Number of methods executed against each of repositories, gives an idea of traffic on each collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "increase(spring_data_repository_invocations_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{repository}} - {{method}}"
    }
   ]
  },
  {
   "title": "Repository Method Avg Execution Time",
   "type": "piechart",
   "description": "Total time taken per method per repository, a high value indicates perf issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(spring_data_repository_invocations_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])/increase(spring_data_repository_invocations_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{repository}} - {{method}}"
    }
   ]
  },
  {
   "title": "Repository Method Execution Max Time",
   "type": "timeseries",
   "description": "Max recorded time of each mongo operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_max{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{repository}} - {{method}}"
    }
   ]
  },
  {
   "title": "Time in Seconds of Operations Per Collection",
   "type": "timeseries",
   "description": "The maximum time in seconds it took to execute a particular command on a MongoDB collection. This is the worst case unit. You can use it to identify the slowest operations per collection in your app.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(mongodb_driver_commands_seconds_sum{pod=~\"$pod\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}} | {{command}} | {{collection}}"
    }
   ]
  },
  {
   "title": "Number of Commands Per collection Per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "increase(mongodb_driver_commands_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Operations Average Time Per Collection",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mongodb_driver_commands_seconds_sum{pod=~\"$pod\", namespace=~\"$namespace\"}[$__rate_interval])/increase(mongodb_driver_commands_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{ collection }} - {{command}}"
    }
   ]
  },
  {
   "title": "Mongo Operation Max Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_driver_commands_seconds_max{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Mongodb Driver Pool Waitqueuesize",
   "type": "timeseries",
   "description": "The current size of the wait queue for a connection from the pool",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "mongodb_driver_pool_waitqueuesize{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} | {{namespace}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "domain-data-api-9857d678d-56ssd"
       },
       { "label": "namespace", "op": "=", "value": "dev" }
      ],
      "metric": "mongodb_driver_commands_seconds_max",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Mongodb Driver Pool Checkedout",
   "type": "timeseries",
   "description": "Count of connections that are currently in use",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_driver_pool_checkedout{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "domain-data-api-9857d678d-56ssd"
       },
       { "label": "namespace", "op": "=", "value": "dev" }
      ],
      "metric": "mongodb_driver_commands_seconds_max",
      "operations": []
     }
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=~\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "CPU time used by GC",
   "type": "stat",
   "description": "An approximation of the percent of CPU time used by GC activities over the last lookback period or since monitoring began, whichever is shorter, in the range [0..1]",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap Gain Byte Size",
   "type": "stat",
   "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM GC Max Data Size Bytes",
   "type": "stat",
   "description": "Max size of long-lived heap memory pool",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Long Lived Heap Pool",
   "type": "stat",
   "description": "Size of long-lived heap memory pool after reclamation",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Gc Pause Duration In Seconds",
   "type": "timeseries",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Action: {{action}} | Cause: {{cause}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "CodeHeap 'profiled nmethods'",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", area=\"nonheap\", id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-profiled nmethods'",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", area=\"nonheap\", id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", area=\"nonheap\",area=\"nonheap\",id=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", area=\"nonheap\",area=\"nonheap\",id=\"Metaspace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-nmethods'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", area=\"nonheap\",area=\"nonheap\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{pod=~\"$pod\",namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{pod=~\"$pod\", namespace=~\"$namespace\", id=~\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}