{
 "title": "NH44",
 "tags": [
  "Fabric",
  "JVM"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer Connection Count Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_connection_count_total{pod=~\"$pod\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumer Records / Request",
   "type": "stat",
   "description": "The average number of records in each request per topic, select pod to see details.",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_per_request_avg{pod=\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Consumer Total Requests",
   "type": "stat",
   "description": "The total number of fetch requests.\n",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(kafka_consumer_fetch_manager_fetch_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Consumer Failed Auth",
   "type": "stat",
   "description": "The total number of failed authentications for this consumer (sum of failures on all client IDs)\n",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_failed_reauthentication_rate{namespace=~\"$namespace\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Producer Connection Count Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_producer_connection_count_total{pod=~\"$pod\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Producer Records / Request",
   "type": "stat",
   "description": "The average number of records in each request, select pod to see details.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{namespace=~\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Producer Total Requests",
   "type": "stat",
   "description": "The total number of fetch requests.\n",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_producer_record_send_rate{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Producer Failed Auth",
   "type": "stat",
   "description": "The total number of connections with failed auth",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_producer_failed_authentication_rate{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Producer Error Rate by Topic",
   "type": "stat",
   "description": "Producer error per topic,  select a pod to view details",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_error_rate{namespace=~\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Rebalancing Failure Rate Per Hour",
   "type": "bargauge",
   "description": "Choose Pod to see rebalancing rate. High rebalancing rate is a potential perf problem.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Rebalancing Success Rate Per Hour",
   "type": "bargauge",
   "description": "Choose Pod to see rebalancing rate. High rebalancing rate is a potential perf problem.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Partitions Assigned Per Consumer",
   "type": "bargauge",
   "description": "Lag is the delta between the last produced message and the last committed message of a partition. In other words, lag indicates how far behind your application is in processing up-to-date information.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_assigned_partitions{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ app_kubernetes_io_service }} | {{ client_id}}"
    }
   ]
  },
  {
   "title": "Kafka Partition Average Lag",
   "type": "timeseries",
   "description": "Lag is the delta between the last produced message and the last committed message of a partition. In other words, lag indicates how far behind your application is in processing up-to-date information.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_avg{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ app_kubernetes_io_service }}"
    }
   ]
  },
  {
   "title": " Kafka Consumer Requests Per Minute Rate",
   "type": "timeseries",
   "description": "The rate of Kafka consumer requests per minute",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kafka_consumer_request_rate{namespace=~\"$namespace\", pod=~\"$pod\"} * 60",
     "legendFormat": "Clinet ID: {{client_id}}"
    }
   ]
  },
  {
   "title": " Kafka Consumer Responses Per Minute Rate",
   "type": "timeseries",
   "description": "The rate of Kafka consumer requests per minute",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kafka_consumer_response_rate{namespace=~\"$namespace\", pod=~\"$pod\"} * 60",
     "legendFormat": "Clinet ID: {{client_id}}"
    }
   ]
  },
  {
   "title": "Average Message Processing Time ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_kafka_listener_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(spring_kafka_listener_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": " Kafka Records Consumed/Min Rate",
   "type": "timeseries",
   "description": "The average number of records consumed per second for a topic.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{pod=~\"$pod\", namespace=~\"$namespace\"} * 60",
     "legendFormat": "{{pod}} | Topic: {{topic}} | Clinet ID: {{client_id}} | Spring ID:{{spring_id}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Requests/Min Rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{namespace=~\"$namespace\",pod=~\"$pod\"} * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency Max",
   "type": "timeseries",
   "description": "The max time taken for any fetch request.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}} | {{pod}}",
     "visualQuery": {
      "labels": [
       {
        "label": "pod",
        "op": "=",
        "value": "nightly-domain-data-api-5d75b6dc4-wpzx4"
       }
      ],
      "metric": "kafka_consumer_outgoing_byte_total",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency Avg",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{pod}}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Average Latecy",
   "type": "timeseries",
   "description": "The average time taken by a Kafka producer node to complete a request to a broker. A high value for this metric can indicate potential issues with network or broker performance, while a low value can indicate that the system is operating efficiently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_latency_avg{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Topic Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_error_rate{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Error Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_retry_rate{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Waiting Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "kafka_producer_waiting_threads{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  }
 ]
}