{
 "title": "Node Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mongodb_connections_available, cl_name)"
    }
   },
   {
    "name": "replicaSet",
    "query": {
     "query": "label_values(mongodb_connections_available, rs_nm)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(mongodb_connections_available, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "increase(hardware_disk_metrics_read_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "increase(hardware_disk_metrics_write_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "N/W Data Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(hardware_system_network_eth0_bytes_in_bytes{job=\"$job\"}[$__range])",
     "legendFormat": "In",
     "visualQuery": {
      "labels": [],
      "metric": "hardware_system_vm_page_swap_in",
      "operations": []
     }
    },
    {
     "expr": "rate(hardware_system_network_eth0_bytes_out_bytes{job=\"$job\"}[$__range])",
     "legendFormat": "Out",
     "visualQuery": {
      "labels": [],
      "metric": "hardware_system_vm_page_swap_in",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(hardware_system_memory_cached_kilobytes{job=\"$job\"}[$__range])",
     "legendFormat": "{{job}}",
     "visualQuery": {
      "labels": [],
      "metric": "hardware_system_vm_page_swap_in",
      "operations": []
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage on MongoDB Nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$__rate_interval])) * 100)"
    }
   ]
  }
 ]
}