{
 "title": "Oauth",
 "description": "Swagger-Stats Main Dashboard Revision  3",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_all_request_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( api_all_errors_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"} / api_all_request_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"} ) * 100"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_all_request_in_processing_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage{instance=\"gringotts.oauth.svc.cluster.local:9000\"}"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_process_memory_heap_used_bytes{instance=\"gringotts.oauth.svc.cluster.local:9000\"})/1048576"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(api_all_request_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"}[1m])",
     "visualQuery": {
      "labels": [
       {
        "label": "instance",
        "op": "=",
        "value": "gringotts.oauth.svc.cluster.local:9000"
       }
      ],
      "metric": "api_all_request_total",
      "operations": [
       { "id": "rate", "params": [ "1m" ] }
      ]
     }
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"5\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"10\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"50\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"100\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  },
  {
   "title": "Request Rate By Response Codes (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_request_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"}[1m])) by (code)"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(api_request_total{instance=\"gringotts.oauth.svc.cluster.local:9000\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(api_request_total[1m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total{code=~\"^5..$\"}[1m])) by (path))"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total[1m])) by (path))"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "  sum by (path, method, code) (\n    rate(api_request_duration_milliseconds_count[1m])\n  ) >= 100",
     "visualQuery": {
      "labels": [],
      "metric": "api_request_duration_milliseconds_count",
      "operations": [
       { "id": "rate", "params": [ "5m" ] },
       {
        "id": "__sum_by",
        "params": [
         "instance",
         "method",
         "code"
        ]
       }
      ]
     }
    }
   ]
  }
 ]
}